version: '3'

services:
  python:
    container_name: python
    build:
      context: ./src
      dockerfile: Dockerfile.local
    working_dir: /opt/src
    tty: true
    volumes:
      - ./src:/opt/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33063:3306
    volumes:
      - ./mysql/db-store:/var/lib/mysql
    env_file:
      - .env